[package]
name = "plain_hasher"
description = "Hasher for 32-bit keys."
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
keywords = ["hash", "hasher"]
homepage = "https://github.com/paritytech/plain_hasher"

[dependencies]
crunchy = "0.1.6"
ethereum-types = { version = "0.3", optional = true }

[features]
default = ["std"]
std = ["ethereum-types"]