environment:
  matrix:
  - FEATURES: ""

platform:
  - x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:PLATFORM}.exe"
  - rust-nightly-%PLATFORM%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo check --tests --features "%FEATURES%"
  - cargo build --all --features "%FEATURES%"

test_script:
  - cargo test --all --features "%FEATURES%" --exclude uint --exclude fixed-hash
  - cd fixed-hash/ && cargo test --all-features && cd ..
  - cd uint/ && cargo test --features=std,impl_quickcheck_arbitrary --release && cd ..
  - cd hashdb/ && cargo test --no-default-features && cd ..
  - cd plain_hasher/ && cargo test --no-default-features && cd ..
