environment:
  matrix:
  - FEATURES: ""

platform:
  - i686-pc-windows-msvc
  - x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:PLATFORM}.exe"
  - rust-nightly-%PLATFORM%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo check --tests --features "%FEATURES%"
  - cargo build --all --features "%FEATURES%"

test_script:
  - cargo test --all --features "%FEATURES%" --exclude uint --exclude fixed-hash
