[package]
name = "impl-serde"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
homepage = "https://github.com/paritytech/parity-common"
description = "Serde serialization support for uint and fixed hash."

[dependencies]
serde = "1.0"
rustc-hex = "2.0.1"
