[package]
name = "kvdb-shared-tests"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Shared tests for kvdb functionality, to be executed against actual implementations"
license = "MIT OR Apache-2.0"

[dependencies]
kvdb = { path = "../kvdb", version = "0.10" }
