[package]
name = "trace-time"
description = "Easily trace time to execute a scope."
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.8"
