[package]
name = "impl-rlp"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/paritytech/parity-common"
description = "RLP serialization support for uint and fixed hash."
edition = "2021"
rust-version = "1.56.1"

[dependencies]
rlp = { version = "0.6", path = "../../../rlp", default-features = false }

[features]
default = ["std"]
std = ["rlp/std"]
