[package]
name = "hashdb"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "trait for hash-keyed databases."
license = "GPL-3.0"

[dependencies]

[features]
default = ["std"]
std = []
