[package]
name = "impl-codec"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
homepage = "https://github.com/paritytech/parity-common"
description = "Parity Codec serialization support for uint and fixed hash."

[dependencies]
parity-codec = { version = "2.1", default-features = false }

[features]
default = ["std"]
std = ["parity-codec/std"]
