[package]
name = "patricia-trie-ethereum"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie (Ethereum Style)"
license = "GPL-3.0"

[dependencies]
patricia-trie = { version = "0.3.0-beta", path = "../../patricia_trie" }
keccak-hasher = { version = "0.1", path = "../keccak-hasher" }
hashdb = { version = "0.3.0-beta", path = "../../hashdb" }
rlp = { version = "0.3.0-beta", path = "../../rlp" }
parity-bytes = { version = "0.1", path = "../../parity-bytes" }

ethereum-types = "0.4"
elastic-array = "0.10"
