[package]
name = "fixed-hash"
version = "0.5.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/parity-common"
repository = "https://github.com/paritytech/parity-common"
description = "Macros to define custom fixed-size hash types"
documentation = "https://docs.rs/fixed-hash/"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
features = ["quickcheck", "api-dummy"]

[dependencies]
byteorder = { version = "1.3.2", optional = true, default-features = false }
quickcheck = { version = "0.9.0", optional = true }
rand = { version = "0.7.2", optional = true, default-features = false }
rustc-hex = { version = "2.0.1", optional = true, default-features = false }
static_assertions = "1.0.0"

[dev-dependencies]
rand_xorshift = "0.2.0"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
libc = { version = "0.2.64", optional = true, default-features = false }

[features]
default = ["std", "libc", "rand", "rustc-hex", "byteorder"]
std = ["rustc-hex/std", "rand/std", "byteorder/std"]

api-dummy = [] # Feature used by docs.rs to display documentation of hash types
