[package]
name = "fixed-hash"
version = "0.2.4"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/parity-common"
repository = "https://github.com/paritytech/parity-common"
description = "Fixed-size hashes"

[dependencies]
heapsize = { version = "0.4", optional = true }
rand = { version = "0.4", optional = true }
rustc-hex = { version = "2.0", optional = true }
quickcheck = { version = "0.7", optional = true }
static_assertions = "0.2"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
libc = { version = "0.2", optional = true, default-features = false }

[features]
default = ["std", "libc"]
std = ["rustc-hex", "rand"]
heapsizeof = ["heapsize"]
impl_quickcheck_arbitrary = ["quickcheck"]
